"""Produce a reviewable, policy-oriented Markdown report for a data release."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


MINIMUM_TASKS = 10


def status(ok: bool) -> str:
    return "✅ PASS" if ok else "❌ BLOCK"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text())
    task_count = int(manifest.get("task_count", 0))
    annotated = int(manifest.get("annotated_task_count", 0))
    empty = int(manifest.get("empty_annotation_count", 0))
    unannotated = int(manifest.get("unannotated_task_count", 0))
    labels = {str(key): int(value) for key, value in manifest.get("label_counts", {}).items()}
    gates = [
        ("Schema version is supported", manifest.get("schema_version") == 1),
        ("At least one task is present", task_count > 0),
        ("All exported tasks are annotated", annotated == task_count and unannotated == 0),
        ("No empty active annotations", empty == 0),
        ("At least two labels are represented", len(labels) >= 2),
    ]
    passed = all(result for _, result in gates)
    low_sample_warning = task_count < MINIMUM_TASKS
    counts = list(labels.values())
    imbalance = max(counts) / min(counts) if counts and min(counts) else 0
    warnings = []
    if low_sample_warning:
        warnings.append(f"Only {task_count} tasks; local demo threshold is {MINIMUM_TASKS}, production training needs a larger policy-defined sample.")
    if imbalance >= 10:
        warnings.append(f"Class imbalance ratio is {imbalance:.1f}:1; inspect minority-class coverage before training.")
    if not warnings:
        warnings.append("No advisory warnings from the local data-release policy.")

    rows = "\n".join(f"| {name} | {status(result)} |" for name, result in gates)
    class_rows = "\n".join(f"| `{label}` | {count} |" for label, count in sorted(labels.items(), key=lambda item: (-item[1], item[0])))
    decision = "✅ APPROVE FOR CANDIDATE TRAINING" if passed else "❌ BLOCK DATA RELEASE"
    report = f"""## MLForge data-release review

### Decision: {decision}

This report is generated by the release policy and posted by CML. The PR approver remains responsible for accepting the data version.

### Quality gates

| Gate | Result |
| --- | --- |
{rows}

### Coverage and distribution

| Metric | Value |
| --- | ---: |
| Tasks | {task_count} |
| Active annotations | {manifest.get('active_annotation_count', 0)} |
| Annotated tasks | {annotated} |
| Empty annotations | {empty} |
| Label classes | {len(labels)} |
| Largest/smallest class ratio | {imbalance:.1f}:1 |

| Class | Boxes |
| --- | ---: |
{class_rows}

### Advisory warnings

""" + "\n".join(f"- ⚠️ {warning}" for warning in warnings) + f"""

### Lineage and integrity

| Field | Value |
| --- | --- |
| Label Studio project | `{manifest.get('project_id')}` |
| Release ID | `{manifest.get('release_id')}` |
| Manifest | `{args.manifest}` |
| Dataset SHA-256 | `{manifest.get('sha256')}` |
| Schema | `{manifest.get('schema_version')}` |

<details><summary>Raw manifest</summary>

```json
{json.dumps(manifest, indent=2, sort_keys=True)}
```
</details>
"""
    args.output.write_text(report)
    print(json.dumps({"result": "pass" if passed else "block", "warnings": len(warnings)}))


if __name__ == "__main__":
    main()
